version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knife-shop-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - knife-shop-network

  nginx:
    image: nginx:alpine
    container_name: knife-shop-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - knife-shop-network

  db:
    image: mysql:8.0
    container_name: knife-shop-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: knife_shop
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: user
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - knife-shop-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: knife-shop-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - knife-shop-network

  vite:
    build:
      context: .
      dockerfile: Dockerfile.vite
    container_name: knife-shop-vite
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    networks:
      - knife-shop-network
    command: sh -c "npm install && npm run dev"

networks:
  knife-shop-network:
    driver: bridge

volumes:
  dbdata:
